"""initial profile persistence

Revision ID: 22dad79c2ee1
Revises:
Create Date: 2026-10-03 17:41:29.880199
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22dad79c2ee1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_timezone", sa.String(length=64), nullable=False),
        sa.Column("lifecycle", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lifecycle IN ('active', 'disabled')", name="ck_users_lifecycle"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("external_namespace", sa.String(length=120), nullable=True),
        sa.Column("external_identifier", sa.String(length=256), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('manual', 'device', 'document', 'provider', 'ai', 'system')",
            name="ck_sources_kind",
        ),
        sa.CheckConstraint(
            "(external_namespace IS NULL) = (external_identifier IS NULL)",
            name="ck_sources_external_identity_pair",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_sources_owner_id"),
        sa.UniqueConstraint("owner_id", "source_key", name="uq_sources_owner_key"),
    )
    op.create_table(
        "health_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("confirmation_status", sa.String(length=24), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ai_use_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "cross_domain_use_allowed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("create_fingerprint", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "confirmation_status IN ('unconfirmed', 'user_confirmed')",
            name="ck_health_objects_confirmation",
        ),
        sa.CheckConstraint("domain = 'profile'", name="ck_health_objects_domain_phase1"),
        sa.CheckConstraint("object_type = 'profile_item'", name="ck_health_objects_type_phase1"),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_health_objects_status"),
        sa.CheckConstraint(
            "notes IS NULL OR char_length(notes) <= 4000", name="ck_health_objects_notes"
        ),
        sa.CheckConstraint("revision > 0", name="ck_health_objects_revision"),
        sa.CheckConstraint("schema_version = 1", name="ck_health_objects_schema_version"),
        sa.CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_from < valid_to",
            name="ck_health_objects_validity",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "source_id"],
            ["sources.owner_id", "sources.id"],
            name="fk_health_objects_owner_source",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id", name="uq_health_objects_owner_id"),
    )
    op.create_index(
        "ix_health_objects_owner_status_created",
        "health_objects",
        ["owner_id", "status", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "health_object_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("actor_kind = 'user'", name="ck_health_object_revisions_actor_kind"),
        sa.CheckConstraint(
            "reason IN ('create', 'update', 'archive')", name="ck_health_object_revisions_reason"
        ),
        sa.CheckConstraint("actor_id = owner_id", name="ck_health_object_revisions_owner_actor"),
        sa.CheckConstraint("revision > 0", name="ck_health_object_revisions_revision"),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "object_id"],
            ["health_objects.owner_id", "health_objects.id"],
            name="fk_health_object_revisions_owner_object",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "object_id", "revision", name="uq_health_object_revision"),
    )
    op.create_table(
        "health_relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("from_object_id", sa.Uuid(), nullable=False),
        sa.Column("to_object_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation_type = 'related_to'", name="ck_health_relationships_type_phase1"
        ),
        sa.CheckConstraint(
            "from_object_id <> to_object_id", name="ck_health_relationships_not_self"
        ),
        sa.CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_from < valid_to",
            name="ck_health_relationships_validity",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "from_object_id"],
            ["health_objects.owner_id", "health_objects.id"],
            name="fk_health_relationships_owner_from",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "source_id"],
            ["sources.owner_id", "sources.id"],
            name="fk_health_relationships_owner_source",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "to_object_id"],
            ["health_objects.owner_id", "health_objects.id"],
            name="fk_health_relationships_owner_to",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id",
            "from_object_id",
            "to_object_id",
            "relation_type",
            name="uq_health_relationships_edge",
        ),
    )
    op.create_index(
        "ix_health_relationships_owner_from",
        "health_relationships",
        ["owner_id", "from_object_id"],
        unique=False,
    )
    op.create_index(
        "ix_health_relationships_owner_to",
        "health_relationships",
        ["owner_id", "to_object_id"],
        unique=False,
    )
    op.create_table(
        "profile_items",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(kind = 'fact' AND category = 'background') OR (kind = 'constraint' AND category = 'constraints') OR (kind = 'preference' AND category = 'preferences')",
            name="ck_profile_items_kind_category",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object' AND payload->>'kind' = kind AND payload->>'category' = category AND payload->>'key' = key",
            name="ck_profile_items_payload_consistency",
        ),
        sa.CheckConstraint("key ~ '^[a-z][a-z0-9_]{0,63}$'", name="ck_profile_items_key"),
        sa.ForeignKeyConstraint(
            ["owner_id", "object_id"],
            ["health_objects.owner_id", "health_objects.id"],
            name="fk_profile_items_owner_object",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("owner_id", "object_id"),
    )
    op.create_index(
        "ix_profile_items_owner_category_key",
        "profile_items",
        ["owner_id", "category", "key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profile_items_owner_category_key", table_name="profile_items")
    op.drop_table("profile_items")
    op.drop_index("ix_health_relationships_owner_to", table_name="health_relationships")
    op.drop_index("ix_health_relationships_owner_from", table_name="health_relationships")
    op.drop_table("health_relationships")
    op.drop_table("health_object_revisions")
    op.drop_index("ix_health_objects_owner_status_created", table_name="health_objects")
    op.drop_table("health_objects")
    op.drop_table("sources")
    op.drop_table("users")
    # ### end Alembic commands ###
