import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f7f9f7" },
  content: { gap: 16, padding: 20, paddingBottom: 36 },
  title: { color: "#17201c", fontSize: 28, fontWeight: "700" },
  subtitle: { color: "#46534d", fontSize: 15, lineHeight: 22 },
  sectionTitle: { color: "#203a2e", fontSize: 20, fontWeight: "700" },
  cardTitle: { color: "#17201c", fontSize: 18, fontWeight: "700" },
  body: { color: "#46534d", fontSize: 14, lineHeight: 20 },
  inputGroup: { gap: 6 },
  inputLabel: { color: "#203a2e", fontSize: 15, fontWeight: "700" },
  input: {
    backgroundColor: "#fff",
    borderColor: "#68786f",
    borderRadius: 10,
    borderWidth: 1,
    color: "#17201c",
    fontSize: 16,
    minHeight: 50,
    paddingHorizontal: 14,
  },
  choices: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: {
    backgroundColor: "#fff",
    borderColor: "#68786f",
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  choiceSelected: { backgroundColor: "#245d3a", borderColor: "#245d3a" },
  choiceText: { color: "#24342b", fontSize: 14, textTransform: "capitalize" },
  choiceTextSelected: { color: "#fff", fontWeight: "700" },
  fieldCard: {
    backgroundColor: "#eaf0ec",
    borderRadius: 14,
    gap: 12,
    padding: 14,
  },
  multiline: { minHeight: 90, paddingTop: 12, textAlignVertical: "top" },
  targetChoice: {
    backgroundColor: "#fff",
    borderRadius: 10,
    gap: 4,
    padding: 12,
  },
  targetChoiceSelected: { borderColor: "#245d3a", borderWidth: 2 },
  itemRow: { backgroundColor: "#fff", borderRadius: 10, gap: 10, padding: 12 },
  cardMain: { gap: 4 },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  note: { backgroundColor: "#eaf0ec", borderRadius: 12, padding: 14 },
  noteText: { color: "#46534d", fontSize: 14, lineHeight: 21 },
});
