import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f7f9f7" },
  content: { gap: 16, padding: 20, paddingBottom: 48 },
  header: { gap: 8, paddingVertical: 8 },
  title: { color: "#17201c", fontSize: 30, fontWeight: "700" },
  body: { color: "#46534d", fontSize: 16, lineHeight: 23 },
  section: {
    backgroundColor: "#edf3ef",
    borderRadius: 16,
    gap: 12,
    padding: 16,
  },
  sectionTitle: { color: "#17201c", fontSize: 21, fontWeight: "700" },
  help: { color: "#596860", fontSize: 14, lineHeight: 20 },
  summary: { color: "#17201c", fontSize: 17, fontWeight: "700" },
  choices: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: {
    backgroundColor: "#fff",
    borderColor: "#aab8af",
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  choiceSelected: { backgroundColor: "#245d3a", borderColor: "#245d3a" },
  choiceText: { color: "#24342b", fontSize: 14 },
  choiceTextSelected: { color: "#fff", fontWeight: "700" },
  field: { flex: 1, gap: 5, minWidth: 120 },
  fieldLabel: { color: "#34463b", fontSize: 14, fontWeight: "600" },
  input: {
    backgroundColor: "#fff",
    borderColor: "#aab8af",
    borderRadius: 10,
    borderWidth: 1,
    color: "#17201c",
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  multiline: { minHeight: 88, textAlignVertical: "top" },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tableHeading: {
    color: "#34463b",
    fontSize: 15,
    fontWeight: "700",
    marginTop: 6,
  },
  tableRow: {
    borderTopColor: "#d4dfd8",
    borderTopWidth: 1,
    gap: 2,
    paddingVertical: 8,
  },
  tableDate: { color: "#17201c", fontSize: 15, fontWeight: "600" },
  tableValue: { color: "#24342b", fontSize: 16 },
  tableMeta: { color: "#596860", fontSize: 13 },
  card: {
    backgroundColor: "#fff",
    borderColor: "#c8d2cb",
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  cardTitle: { color: "#17201c", fontSize: 17, fontWeight: "700" },
  cardBody: { color: "#34463b", fontSize: 15, lineHeight: 21 },
  result: {
    borderTopColor: "#d4dfd8",
    borderTopWidth: 1,
    gap: 6,
    paddingTop: 8,
  },
  evidenceLink: {
    alignSelf: "flex-start",
    justifyContent: "center",
    minHeight: 36,
  },
  evidenceText: {
    color: "#245d3a",
    fontSize: 13,
    textDecorationLine: "underline",
  },
});
