import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: { gap: 18, padding: 20, paddingBottom: 48 },
  title: { color: "#17201c", fontSize: 28, fontWeight: "700" },
  body: { color: "#46534d", fontSize: 16, lineHeight: 23 },
  hint: { color: "#4d5a54", fontSize: 14, lineHeight: 20 },
  section: {
    backgroundColor: "#edf2ee",
    borderRadius: 14,
    gap: 12,
    padding: 16,
  },
  notice: {
    backgroundColor: "#fff",
    borderColor: "#c9d7cd",
    borderRadius: 14,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  statusCard: {
    backgroundColor: "#fff4db",
    borderRadius: 14,
    gap: 8,
    padding: 16,
  },
  readyCard: { backgroundColor: "#dcefe4" },
  errorCard: {
    backgroundColor: "#fff",
    borderColor: "#9b1c1c",
    borderRadius: 14,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  errorText: { color: "#9b1c1c", fontSize: 15, lineHeight: 22 },
  sectionTitle: { color: "#203a2e", fontSize: 19, fontWeight: "700" },
  switchRow: {
    alignItems: "center",
    borderBottomColor: "#d2ddd5",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    minHeight: 54,
  },
  switchLabel: { color: "#24342b", flex: 1, fontSize: 16 },
  fieldLabel: { color: "#203a2e", fontSize: 16, fontWeight: "700" },
  input: {
    backgroundColor: "#fff",
    borderColor: "#68786f",
    borderRadius: 10,
    borderWidth: 1,
    color: "#17201c",
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  multiline: { minHeight: 110, textAlignVertical: "top" },
  choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#68786f",
    borderRadius: 22,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 14,
  },
  choiceSelected: {
    backgroundColor: "#dcefe4",
    borderColor: "#245d3a",
    borderWidth: 2,
  },
  choiceText: { color: "#24342b", fontSize: 14, fontWeight: "600" },
  choiceTextSelected: { color: "#17492b" },
  button: {
    alignItems: "center",
    backgroundColor: "#245d3a",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 50,
    paddingHorizontal: 18,
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  disabled: { opacity: 0.55 },
  entry: {
    backgroundColor: "#fff",
    borderColor: "#d2ddd5",
    borderRadius: 12,
    borderWidth: 1,
    gap: 7,
    padding: 12,
  },
  evidenceList: { gap: 4 },
  proposalCommand: {
    backgroundColor: "#f5f8f5",
    borderColor: "#d2ddd5",
    borderRadius: 10,
    borderWidth: 1,
    gap: 6,
    padding: 10,
  },
  proposalActions: { gap: 8 },
  editor: { gap: 10 },
  commandEditor: {
    minHeight: 240,
    textAlignVertical: "top",
    fontFamily: "monospace",
    fontSize: 13,
  },
  summaryCard: {
    backgroundColor: "#fff",
    borderColor: "#d2ddd5",
    borderRadius: 12,
    borderWidth: 1,
    gap: 7,
    padding: 12,
  },
  summaryText: { color: "#24342b", fontSize: 14, lineHeight: 20 },
  entryTitle: { color: "#17201c", fontSize: 16, fontWeight: "700" },
  payload: { color: "#24342b", fontSize: 14, lineHeight: 20 },
  warning: { color: "#755006", fontSize: 14, lineHeight: 20 },
  linkRow: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  textLink: {
    color: "#245d3a",
    fontSize: 15,
    fontWeight: "700",
    paddingVertical: 8,
  },
});
